### PR TITLE
feat(redwood): add nau learning header customization

### PR DESCRIPTION
**Pull request by dcoa**
This PR migrates the custom NAU header changes to the Redwood version. 

image

**How to test**

1. Create a tutor redwood environment.
2.  Inside your environment clone the learning MFE and mount it with `tutor mounts add ./frontend-app-learning`.
3. Inside the learning MFE, clone the header repository with the current branch (remember to run `npm install` for both, the learning app and the header).
4. Create the `module.config.js` file and add the following configuration.
```javascript
module.exports = {
  localModules: [
    { moduleName: '@edx/frontend-component-header/dist', dir: './frontend-component-header-nau', dist: 'src' },
    { moduleName: '@edx/frontend-component-header', dir: './frontend-component-header-nau', dist: 'src' },
  ],
};
```
3. Run the command `tutor images build learning-dev`.
4. Start your environment `tutor dev start`.
5. Create a course and configure the organization info inside the LMS admin.
6. Open the courseware and check you can see the changes.

### CODE REVIEW

**Comment by igobranco** [comment]
@dcoa can you fix the lint?

**Review by sandroscosta — APPROVED** [review]

**Comment by sandroscosta** [comment]
Code looks ok but I still need to install quince and run some tests. Would you suggest TVM to have quince installed along side Nutmeg, our previous version?

**Comment by dcoa** [comment]
TVM allows you to have different environments in the same machine without problem, it's a good option for local testing.

**Comment by dcoa** [comment]
Hi @sandroscosta have you been able to run the testing? Do you have any other issues that should be addressed?

**Comment by sandroscosta** [comment]
Hi @dcoa. Ran all the tests. Everything looks fine. The only thing I want to ask you is if you think we should cast our config variable as boolean, like
```javascript
const enabledOrgLogo = !!getConfig().ENABLED_ORG_LOGO || false;
```

The rest of it is all ok.

**Comment by dcoa** [comment]
Hi @sandroscosta, thanks for your review. Answer your question it is been cast as a boolean  in the capturing of the env variable, here

https://github.com/fccn/frontend-component-header-nau/blob/a8789fe9d4bf1b96693e57ea796811384802e589/src/Header.jsx#L31

**Comment by sandroscosta** [comment]
Fantastic. As I didn't see it in this PR, I never went and looked for it elsewhere. I'll just tweak the variable name, as I named it incorrectly in past tense. Would you mind if I do a commit into this branch?

**Comment by sandroscosta** [comment]
@dcoa I think that everything is valid on this PR. I'm going to merge this, if you agree.

**Review by sandroscosta — APPROVED** [review]
LGTM

**Pull request merged**
